name: Crowdin Sync

on:
  # Runs on pushes to main branch
  push:
    branches: [main]
    paths:
      - "src/content/docs/**"
      - "src/content/i18n/en.json"

  # Manual trigger
  workflow_dispatch:

  # Run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin Action
        uses: crowdin/github-action@v2
        with:
          # Upload sources to Crowdin
          upload_sources: true

          # Download translations from Crowdin
          download_translations: true

          # Create pull request
          create_pull_request: true
          pull_request_title: "[i18n] updated translations from Crowdin"
          pull_request_labels: "i18n,crowdin"

          # Configuration
          config: "crowdin.yml"

          # Localization branch name
          localization_branch_name: l10n_crowdin_translations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
